org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=modid
mod.name=ModId Name
mod.group=net.mat0u5
mod.version=1.0.0
mod.version_prefix=
mod.version_suffix=
mod.authors=Mat0u5
mod.contributors=
mod.license=MIT
mod.description=ModId Description
mod.sources_url=https://github.com/Mat0u5/ModId
mod.homepage_url=https://github.com/Mat0u5/ModId
mod.issues_url=https://github.com/Mat0u5/ModId/issues
mod.discord_url=https://discord.gg/QWJxfb4zQZ

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]

# Publishing
publish.dryrun=false
publish.changelog.link=https://mat0u5.github.io/...

publish.modrinth.id=
publish.curseforge.id=

publish.modrinth=true
publish.curseforge=true
publish.github=true
publish.discord=false

publish.release.fabric=stable
publish.release.neoforge=beta
publish.release.forge=alpha

publish.github.prerelease=false
publish.github.branch=multiloader-stonecutter
publish.github.target=Mat0u5/FabricModTemplate

publish.discord.dev=false
