modLoader = "javafml"
loaderVersion = "[1,)"
license = "Insert License Here"

[[mods]]
modId = "modid"
version = "${version}"
displayName = "Example Mod (NeoForge)"
authors = "Me!"
description = '''
This is the NeoForge version of my mod!
'''

[[dependencies.modid]]
modId = "neoforge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.modid]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.modid]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "modid-common.mixins.json"

[[mixins]]
config = "modid.mixins.json"